name: 'my_snowflake_dbt_project'
version: '1.0.0'
config-version: 2


profile: 'snowflake_demo_project'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


on-run-end:
  - "{{ grant_all_on_schemas(schemas, 'public') }}"


seeds:
  +quote_columns: false


models:
  my_snowflake_dbt_project:
      staging:
          
          +materialized: view
          
          schema: staging
          
          query_tag: staging
          
          snowflake_warehouse: PC_DBT_WH

          tags: "daily"
          
      marts:
        core:

          +materialized: table
          
          query_tag: marts
          
